title: <font size="5"> Jiawei Xue</font> 
# logo: "/pic2.png?raw=true" 
description:  # your text below (remove <br> elements if you don't need line breaks)
  Dear friends, nice to meet you!    
  <br><br>
  I am Jiawei Xue and have joined  <a href="https://www.alibaba.com/">Alibaba Group</a> as a Senior Algorithm Engineer in Sept. 2024.
  I earned a Ph.D. (2024) and Master’s degree (2020) from Purdue University, and a Bachelor’s degree (2018) from Tsinghua University. 
  My research directions include recommendation, machine learning, urban science, and transportation engineering.
  
  <br><br>
  Please find my <a href="JiaweiXue-CV-20230106.pdf">CV (January 2023)</a>, 
  <a href="https://scholar.google.com/citations?hl=en&user=YPwRH50AAAAJ&view_op=list_works&sortby=pubdate">Google Scholar</a>,
  <a href="https://www.researchgate.net/profile/Jiawei-Xue-6/research">ResearchGate</a>,
  <a href="https://www.linkedin.com/in/jiawei-xue/">LinkedIn</a>.

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
