title: Jiawei Xue
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am Jiawei Xue 1.
  <br><br>
  I am Jiawei Xue 2.
  <br><br>
  <a href="https://www.linkedin.com/in/jiawei-xue/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
