title: Jiawei Xue
logo: "/fig.png?raw=true" 
description:  # your text below (remove <br> elements if you don't need line breaks)
  Dear friends, nice to meet you!    
  <br><br>
  I am Jiawei Xue, a Ph.D. candicate in Lyles School of Civil Engineering, Purdue University.       
  I am working on interesting research problems in (1) Artificial Intelligence for Urban Science; (2) Network Science; (3) Transportation Modelling and Optimization with Prof. Satish V. Ukkusuri.   
  I obtained my M.S.E from Purdue University in 2020 and my B.E. degree from Tsinghua University in 2018.    
  <br><br>
  Please find my <a href="https://purdue.app.box.com/file/970035688754?s=2ti19mz9cyf963midvou9gbuve8condi">CV (June 2022)</a>, 
  <a href="<a href="https://purdue.app.box.com/file/970035688754?s=2ti19mz9cyf963midvou9gbuve8condi">Google Scholar</a>,
  <a href="https://www.linkedin.com/in/jiawei-xue/">LinkedIn</a>,
  <a href="https://www.researchgate.net/profile/Jiawei-Xue-6/research">ResearchGate</a>.
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
